#! /bin/sh

$HOME/.config/desktop.sh &
pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor -d I II III IV V VI VII VIII
kitty zsh -c "calcurse" &

bspc config border_width			3
bspc config window_gap				10
bspc config split_ratio				0.50
bspc config borderless_monocle		true
bspc config gapless_monocle			true
bspc config normal_border_color		"#000000"
bspc config focused_border_color	"#20066F"
bspc config active_border_color		"#024364"
bspc config presel_feedback_color	"#20066F"
bspc config focus_follows_pointer	true
bspc config pointer_follows_focus	true
bspc config pointer_modifier		shift
bspc config automatic_scheme		longest_side
bspc config left_padding			238

bspc rule -a Screenkey manage=off
bspc rule -a rofi state=floating focus=on
bspc rule -a conky state=pseudo_tiled private=on sticky=on
bdpc rule -a dropdown_calcurse state=floating focus=on
